### PR TITLE
Bump Bitcoin Core version to 24.0

### PR DESCRIPTION
**Pull request by jdogresorg**

### CODE REVIEW

**Comment by jotapea** [comment]
@jdogresorg Why was the bitcoin-core software updated? No description was provided...

**Comment by jdogresorg** [comment]
There is a new version of Bitcoin Core 24.0 and Counterparty prefers to stay on the latest version of Bitcoin.

I think it should be pretty obvious what is happening here with the PR description "bump bitcoin core version"... no description necessary.

**Comment by jotapea** [comment]
Counterparty prefers... what does this mean?

I believe that any update to Bitcoin software should have a specific reason, as this software is made to be backward compatible and only users interested in new features should update. Bitcoin is stronger by allowing nodes with older versions of the software to continue working.

I'm just asking the reason, there must be a valid reason to do it. Blindly updating software should be avoided.

**Comment by jdogresorg** [comment]
> Counterparty prefers... what does this mean?

It means that if you look at Counterparty, it has historically stayed on the most recent version of Bitcoin Core since Counterparty was launched in 2014

> I believe blindly updating Bitcoin Core should be avoided.

This is not a blind update, every bitcoin core release comes with additional optimizations, bugfixes, etc... I am of the belief that unless there is a valid reason to NOT update to the latest version of Bitcoin Core, we should stay on the latest version, which currently is 24.0

You can view the Bitcoin Core 24.0 release notes here to see there are numerous improvements.
https://github.com/bitcoin/bitcoin/blob/master/doc/release-notes/release-notes-24.0.md

**Pull request merged**
