### PR TITLE
Indexd backend support

### PR DESCRIPTION
**Pull request by deweller**
support ZMQ for bitcoin

### CODE REVIEW

**Comment by unsystemizer** [comment]
Maybe we could make a change to lower rpcthreads in bitcoin configuration files, to 16 or remove it (default is 4, which gives me the impression it's assumed to be equal to number of cores).

**Comment by unsystemizer** [comment]
I'll give it a try (with these default) in one run "from scratch" on testnet, as I've been looking into these anyway for that indexd bug about lost ZQM messages.

**Comment by deweller** [comment]
After some trial and error, I restored the rpcthreads setting to 16.  The default (4) wasn't enough.  I got messages like this from bitcoind:

`WARNING: request rejected because http work queue depth exceeded, it can be increased with the -rpcworkqueue= setting`

It is possible we should leave the rpcthreads to 4 and increase the rpcworkqueue from the default (16) to something higher.  I'm not sure what the tradeoffs are here.

**Comment by rubensayshi** [comment]
utACK, needs squashing

ACK on the rpcthreads=8/rpcworkqueue=16, but maybe to be sure go with rpcthreads=16/rpcworkqueeu=32 ?

**Pull request merged**
